#!/usr/bin/env python3
# LAN receiver: iPhone Shortcut POSTs a photo/screenshot here, it lands in photos/<date>/<time>.<ext>
# Shortcut posts to:  http://<your-mac>.local:<PORT>/up/<TOKEN>

import os
import datetime
import subprocess
import http.server
import socketserver

# ---- config (edit these) ----
PORT = 8787
BASE = os.path.dirname(os.path.abspath(__file__))
DEST_ROOT = os.path.join(BASE, "photos")          # photos land here, in <date>/ subfolders
TOKEN_FILE = os.path.join(BASE, ".phone-token")   # shared secret; generated by install.sh
LOG = os.path.join(BASE, "phone-receiver.log")
# ------------------------------

with open(TOKEN_FILE) as f:
    TOKEN = f.read().strip()


def log(msg):
    line = "%s  %s\n" % (datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"), msg)
    with open(LOG, "a") as f:
        f.write(line)


def ext_from_bytes(b):
    if b[:8] == b"\x89PNG\r\n\x1a\n":
        return "png"
    if b[:3] == b"\xff\xd8\xff":
        return "jpg"
    if b[:4] == b"RIFF" and b[8:12] == b"WEBP":
        return "webp"
    if b[:4] == b"GIF8":
        return "gif"
    if b[4:12] in (b"ftypheic", b"ftypheix", b"ftypmif1", b"ftypmsf1"):
        return "heic"
    return "png"


class Handler(http.server.BaseHTTPRequestHandler):
    def _resp(self, code, text):
        body = text.encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        parts = self.path.strip("/").split("/")
        if parts and parts[0] == "ping":
            self._resp(200, "pong")
        else:
            self._resp(404, "use POST /up/<token>")

    def do_POST(self):
        client = self.client_address[0]
        clen = self.headers.get("Content-Length", "?")
        log("POST from %s  path=%s  content-length=%s" % (client, self.path, clen))
        parts = self.path.strip("/").split("/")
        if len(parts) < 2 or parts[0] != "up" or parts[1] != TOKEN:
            self._resp(403, "forbidden")
            log("  REJECT bad path/token")
            return
        try:
            length = int(self.headers.get("Content-Length", 0))
        except ValueError:
            length = 0
        if length <= 0:
            self._resp(400, "empty body")
            log("  REJECT empty body")
            return
        body = self.rfile.read(length)
        ext = ext_from_bytes(body)
        now = datetime.datetime.now()
        day = now.strftime("%Y-%m-%d")
        destdir = os.path.join(DEST_ROOT, day)
        os.makedirs(destdir, exist_ok=True)
        base = now.strftime("%H%M%S")
        fname = "%s.%s" % (base, ext)
        i = 1
        while os.path.exists(os.path.join(destdir, fname)):
            fname = "%s_%d.%s" % (base, i, ext)
            i += 1
        path = os.path.join(destdir, fname)
        with open(path, "wb") as fp:
            fp.write(body)
        log("SAVED %s (%d bytes)" % (path, len(body)))

        # iPhone camera photos are usually HEIC; convert to jpg for easy viewing
        if ext in ("heic", "heif"):
            jpgpath = path[:-len(ext)] + "jpg"
            try:
                subprocess.run(
                    ["/usr/bin/sips", "-s", "format", "jpeg", path, "--out", jpgpath],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=20,
                )
                if os.path.exists(jpgpath):
                    os.remove(path)
                    path, fname = jpgpath, os.path.basename(jpgpath)
                    log("converted heic->jpg: %s" % fname)
            except Exception as e:
                log("heic convert failed: %s" % e)

        self._resp(200, "ok %s/%s" % (day, fname))

    def log_message(self, fmt, *args):
        pass


class Server(socketserver.ThreadingMixIn, http.server.HTTPServer):
    daemon_threads = True
    allow_reuse_address = True


if __name__ == "__main__":
    os.makedirs(DEST_ROOT, exist_ok=True)
    log("START on 0.0.0.0:%d  dest=%s" % (PORT, DEST_ROOT))
    Server(("0.0.0.0", PORT), Handler).serve_forever()
